### PR TITLE
Add solution repo for oscarada87

### PR DESCRIPTION
**Pull request by oscarada87**

### CODE REVIEW

**Comment by jorgegonzalez** [comment]
Fix the formatting

**Comment by oscarada87** [comment]
Could you please tell me where do i need to change?

**Comment by jorgegonzalez** [comment]
You changed the projects list to be a table of contents, when there is already a ToC in the top of the document. This is unneeded here.

**Comment by oscarada87** [comment]
Oh! I see! 
I've fixed it. Thank you!

**Pull request merged**
