### PR TITLE
Solution for 99 bottles

### PR DESCRIPTION
**Pull request by IvanShkarbut**
Please add my solution.

### CODE REVIEW

**Comment by IvanShkarbut** [comment]
Thank you

**Comment by JorgeGonzalez** [comment]
Of course. Let me know if you ever need any help.

**Comment by IvanShkarbut** [comment]
Hello again, since you offered to help, I need help, such as a problem here, I solved a lot of them, tell me, where are the python projects for beginner on github, those projects which I found to be very difficult.

**Comment by JorgeGonzalez** [comment]
I don't understand your question. And which projects do you find difficult?

**Comment by IvanShkarbut** [comment]
I'm sorry for my english, it's not my native language, for example when I open one of trending in open source project - there big projects, a lot of files, I do not understand why so many of them, if any of them major, to approach which side?

**Comment by JorgeGonzalez** [comment]
Can you give me an example of a project you're looking at?

Many of the large, popular projects on GitHub are too huge and complicated for beginners to understand.

**Comment by IvanShkarbut** [comment]
I think I found a suitable repository https://github.com/scikit-learn/scikit-learn, on http://scikit-learn.org is described in detail about contributing, I will gradually understand...

**Comment by JorgeGonzalez** [comment]
I see. That looks like a Python module with machine learning applications. That looks like too complicated of a project for a beginner to work on.

**Comment by IvanShkarbut** [comment]
Unfortunately, I also realized that, I learn python for about six months, I will look for a more simple projects, I want to quickly become a contributor

**Pull request merged**
