### PR TITLE
Signed-off-by: Ash0prime <ashishsahu1999@hotmail.com>

### PR DESCRIPTION
**Pull request by Ash0prime**

### CODE REVIEW

**Comment by Ash0prime** [comment]
Why my commit was closed can anyone explain please

**Comment by jorgegonzalez** [comment]
Please compare this PR to previously merged PRs 

https://github.com/jorgegonzalez/beginner-projects#contributing

**Comment by Ash0prime** [comment]
I was going to add more solutions  but you closed the request.

**Comment by jorgegonzalez** [comment]
We no longer accept raw code in this repo. Only links to your repositories.

**Pull request closed without merging**
