### PR TITLE
Added Sierpinski Triangle Question to the set.

### PR DESCRIPTION
**Pull request by anuragkumarak95**

### CODE REVIEW

**Comment by anuragkumarak95** [comment]
changes are done. Name removed from contributing.md file.

**Comment by anuragkumarak95** [comment]
?? should I close this PR ??

**Comment by jorgegonzalez** [comment]
I requested that you delete CONTRIBUTING.md entirely and that you add yourself to the Solutions section in the README.

**Comment by anuragkumarak95** [comment]
***deleted*** the file, sorry if someone asks to delete a file, i always get it confused with delete my changes upon it.... 

deletes are harsh.... :+1:

**Comment by jorgegonzalez** [comment]
Again, you may add your name to the Solutions section in the README, if you wish. Else, I’ll merge this PR as is.

**Comment by anuragkumarak95** [comment]
My name is already there.... look for the last name in solutions section.

**Comment by jorgegonzalez** [comment]
Ah sorry about that then.

**Pull request merged**
